CREATE TABLE IF NOT EXISTS HOME (
	HOME_ID INTEGER PRIMARY KEY,
  MLS_NUMBER TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY TEXT,
  ZIP TEXT,
  SUBDIVISION TEXT,
  SQUARE_FOOTAGE TEXT,
  BEDS INTEGER,
  FULL_BATHS INTEGER,
  HALF_BATHS REAL,
  PRICE REAL NOT NULL,
  DAYS_ON_MARKET INTEGER,
  DESCRIPTION TEXT,
  REALTRACS_IMAGE_LINK TEXT,
  REALTRACS_LINK TEXT
);